class CommandError(Exception):
    pass

class ArgsError(Exception):
    pass